### ISSUE TITLE
quantile_norm snakejob requires more than 32G memory

### ISSUE THREAD

**Issue by mrheinnecker** [jhennies/CebraEM#32]
I just ran into "out_of_memory" issues at the first job submitted by run.py (quantile_norm)
I could not find a way to increase the memory limit in the config files. (maybe I am just too dumb to find it)

I came over it by changing it in the repository file:
CebraEM/cebra-em/cebra_em/snakefiles/run_main.smk 
line 154, position 50

64000 didnt work out either, 
500000 worked

If that does not make sense in any way, maybe something is wrong with my data.
I will follow up on this as soon as the follow up steps work out or not.

Best wishes to you!
Marco

**Comment by mrheinnecker** [comment]
The same issue was with the **run_multicut** job. Here I adjusted the memory limit to 32000 in the snakefile.

But the workflow finished and succesfully produced a segmentation (I will improve it with further iterations). I am very happy.

**Comment by jhennies** [comment]
Hi Marco,

Regarding the memory issue with the normalization job, I assume you are supplying a mask in relatively high resolution. Within this step, the mask is fully loaded into memory such that I recommend using a higher binning. You can set this during project initialization within the mask parameters. (downsample level >1). Anyways, your results will be fine.

For the multicut, sometimes the jobs require quite a lot of memory, hence your solution is fine.

A quick note on the side: consider supplying multiple values for the parameter beta (mc_args) in the segmentation parameters. Then multiple segmentations will be computed with the respective settings and you can check for the best one. You can change this even when you already ran a segmentation within the respective config_seg.json. run.py -t seg will then trigger the additiknal segmentation maps.
