### ISSUE TITLE
Error in rule quantile norm, KeyError: 'quantile_samples' at final segmentation

### ISSUE THREAD

**Issue by masbeckwith** [jhennies/CebraEM#34]
Hi!

I am trying to rerun a segmentation for which the ROI flag was initially not properly set (unit was not defined). For the first run I got no error messages, but upon retrying I get an "error in rule quantile" error message (independent of the ROI flag). It looks like the program is looking for a "quantile_samples" in the config_raw file, which is not there? I tried to manually initiate an empty entry, but it looks like it needs a number, in which case I am not sure what to put.. Is this an issue with rerunning the segmentation or something else on my side? 

<img width="1234" alt="Screenshot 2023-04-17 at 13 25 54" src="https://user-images.githubusercontent.com/84327765/232504822-1dbdb3e7-6968-423d-a5d8-68ce6a2a5d0e.png">

<img width="1235" alt="Screenshot 2023-04-17 at 15 54 46" src="https://user-images.githubusercontent.com/84327765/232505396-6c97b063-0777-4a9f-9e97-5826172d2457.png">

Best wishes,
Marianne

**Comment by jhennies** [comment]
Hi Marianne, could you paste both script calls here?

**Comment by jhennies** [comment]
It does seem broken. I need to look at it to understand what’s going on. Maybe I’ll find some time in the coming days.

**Comment by jhennies** [comment]
Hi Marianne,

It was not your fault. The reason is the latest commit and thus updated code.

You will need to add this line to your config_raw.json:

```
"quantile_samples": 10000,
```

In any freshly generated project this will not be necessary.

Cheers,
Julian
