### ISSUE TITLE
Stitching works only for one beta value per segmentation

### ISSUE THREAD

**Issue by mrheinnecker** [jhennies/CebraEM#45]
I am trying to stitch two datasets of the same segmentation but with different beta values.

To stich, I am using:
run.py -t stitch-cyto_it05 --param beta=0.5 --cluster slurm -c 128 -g 12

This works as it should

If I now want to go also for beta 0.6 with the following call:

run.py -t stitch-cyto_it05 --param beta=0.6 --cluster slurm -c 128 -g 12

Snakemake does not start any jobs and gives me the following output:
![julian3](https://github.com/jhennies/CebraEM/assets/93320404/03f05b12-4491-4ada-b7a2-78c255c2c1e1)

**Comment by jhennies** [comment]
fixed in pull request #66
